describe('Тест страницы Stack', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/stack')
        cy.get('[data-testid="stackInputTest"]').as('input')
        cy.get('[data-testid="stackTestAddBtn"]').as('addBtn')
        cy.get('[data-testid="stackTestDeleteBtn"]').as('deleteBtn')
        cy.get('[data-testid="stackTestClearBtn"]').as('clearBtn')
    });
    it('Кнопка недоступна при пустом инпуте', () => {
        cy.get('@input').should('be.empty')
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.disabled')
        cy.get('@clearBtn').should('be.disabled')
    });

    it('Добавление элемента в стек и анимация работает верно', () => {
        cy.clock()
        cy.get('@input').type('13')
        cy.get('@addBtn').should('be.enabled').click()
        cy.get('[data-testid="circleTest"]').as('circle')
        .should('have.length', 1)
        .eq(0)
        .should('have.css', 'border-color', 'rgb(210, 82, 225)')
        .contains('13')
        cy.get('[data-testid="headTest"]').contains('top')
        cy.get('[data-testid="indexTest"]').eq(0).contains('0')
        cy.tick(500)
        cy.get('[data-testid="circleTest"]')
        .should('have.css', 'border-color', 'rgb(0, 50, 255)')
        .eq(0).contains('13')
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.enabled')
        cy.get('@clearBtn').should('be.enabled')

        cy.get('@input').type('123')
        cy.get('@addBtn').should('be.enabled').click()
        cy.get('[data-testid="headTest"]').eq(0).should('be.empty')
        cy.get('[data-testid="circleTest"]')
        .should('have.length', 2).eq(0).should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('[data-testid="circleTest"]')
        .eq(1).should('have.css', 'border-color', 'rgb(210, 82, 225)').contains('123')
        cy.get('[data-testid="headTest"]').eq(1).contains('top')
        cy.get('[data-testid="headTest"]').eq(0).should('be.empty')
        cy.get('[data-testid="indexTest"]').eq(1).contains('1')
        cy.tick(500)
        cy.get('[data-testid="circleTest"]')
        .eq(1).should('have.css', 'border-color', 'rgb(0, 50, 255)').contains('123')
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.enabled')
        cy.get('@clearBtn').should('be.enabled')
    });

    it('Удаление элемента из стека и анимация работает верно', () => {
        cy.get('@input').type('13')
        cy.get('@addBtn').should('be.enabled').click()
        cy.get('@input').type('123')
        cy.get('@addBtn').should('be.enabled').click()
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.enabled')
        cy.get('@clearBtn').should('be.enabled')
        cy.clock()
        cy.get('[data-testid="circleTest"]').as('circle')
        .should('have.length', 2).eq(1).should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('@deleteBtn').click()
        cy.get('[data-testid="circleTest"]')
        .should('have.length', 2)
        .eq(1).should('have.css', 'border-color', 'rgb(210, 82, 225)').contains('123')
        cy.get('[data-testid="headTest"]').eq(1).contains('top')
        cy.get('[data-testid="indexTest"]').eq(1).contains('1')
        cy.tick(500)
        cy.get('[data-testid="circleTest"]').should('have.length', 1)
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.enabled')
        cy.get('@clearBtn').should('be.enabled')

        cy.get('@deleteBtn').click()
        cy.get('[data-testid="circleTest"]')
        .eq(0).should('have.css', 'border-color', 'rgb(210, 82, 225)').contains('13')
        cy.get('[data-testid="headTest"]').eq(0).contains('top')
        cy.get('[data-testid="indexTest"]').contains('0')
        cy.tick(500)
        cy.get('@addBtn').should('be.disabled')
        cy.get('@deleteBtn').should('be.disabled')
        cy.get('@clearBtn').should('be.disabled')
        cy.get('[data-testid="circleTest"]').should('have.length', 0)
    });
    it('Очистка стека работает верно', () => {
        cy.get('@input').type('13')
        cy.get('@addBtn').should('be.enabled').click()
        cy.get('@input').type('13').type('123')
        cy.get('@addBtn').should('be.enabled').click()
        cy.clock()
        cy.get('[data-testid="circleTest"]')
        .should('have.length', 2).eq(1).should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('@clearBtn').click()
        cy.get('[data-testid="circleTest"]').should('have.length', 0)
    });
});