describe('Тест страницы List', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/list')
        cy.get('[data-testid="listInputValueTest"]').as('inputValue')
        cy.get('[data-testid="listAddToHeadBtn"]').as('addToHeadBtn')
        cy.get('[data-testid="listAddToTailBtn"]').as('addToTailBtn')
        cy.get('[data-testid="listDeleteFromHeadBtn"]').as('deleteFromHeadBtn')
        cy.get('[data-testid="listDeleteFromTailBtn"]').as('deleteFromTailBtn')
        cy.get('[data-testid="listInputIndexTest"]').as('inputIndex')
        cy.get('[data-testid="listAddByIndexBtn"]').as('addByIndex')
        cy.get('[data-testid="listDeleteByIndexBtn"]').as('deleteByIndex')
        cy.get('[data-testid="circleTest"]').as('circle')
        cy.get('[data-testid="arrowTest"]').as('arrow')
        cy.get('[data-testid="headTest"]').as('head')
        cy.get('[data-testid="tailTest"]').as('tail')
        cy.get('[data-testid="indexTest"]').as('index')
    });
    it('Кнопка недоступна при пустом инпуте', () => {
        cy.get('@inputValue').should('be.empty')
        cy.get('@addToHeadBtn').should('be.disabled')
        cy.get('@addToTailBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
        cy.get('@inputIndex').should('be.empty')
        cy.get('@addByIndex').should('be.disabled')
        cy.get('@deleteByIndex').should('be.disabled')
    });
    it('Дефолтный список рендерится верно', () => {
        cy.get('@circle')
        .should('have.length', 4)
        .should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('@arrow')
        .should('have.length', 3)
        cy.get('@head').eq(0).contains('head')
        cy.get('@tail').eq(3).contains('tail')
        cy.get('@index').should('have.length', 4)
    });
    it('Добавление элемента в head работает верно', () => {
        cy.clock()
        cy.get('@circle')
        cy.get('@inputValue').type('1')
        cy.get('@addToHeadBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled')
        cy.get('@addToHeadBtn').should('be.enabled').click()
        cy.get('@addToTailBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.get('[class*=circle_small]')
        .should('have.length', 1)
        .should('have.css', 'border-color', 'rgb(210, 82, 225)')
        .contains('1')
        cy.tick(1000)
        cy.get('[class*=circle_small]').should('not.exist')
        cy.get('@circle')
        .should('have.length', 5)
        .eq(0).should('have.css', 'border-color', 'rgb(127, 224, 81)')
        .contains('1')
        cy.get('@head').eq(0).contains('head')
        /* cy.get('@tail').eq(4).contains('tail') */
        cy.get('@arrow')
        .should('have.length', 4)
        cy.tick(1000)
        cy.get('@circle').should('have.length', 5)
        .eq(0)
        .should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('@inputValue').should('be.empty')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
    it('Добавление элемента в tail работает верно', () => {
        cy.clock()
        cy.get('@circle')
        cy.get('@inputValue').type('5')
        cy.get('@addToHeadBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled').click()
        cy.get('@addToHeadBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.get('[class*=circle_small]')
        .should('have.length', 1)
        .should('have.css', 'border-color', 'rgb(210, 82, 225)')
        .contains('5')
        cy.tick(1000)
        cy.get('[class*=circle_small]').should('not.exist')
        cy.get('@circle')
        .should('have.length', 5)
        .eq(4).should('have.css', 'border-color', 'rgb(127, 224, 81)')
        .contains('5')
        /* cy.get('@tail').eq(3).contains('tail') */
        cy.get('@arrow')
        .should('have.length', 4)
        cy.tick(1000)
        cy.get('@circle').should('have.length', 5)
        .eq(4)
        .should('have.css', 'border-color', 'rgb(0, 50, 255)')
        cy.get('@inputValue').should('be.empty')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    })
    it('Добавление элемента по индексу работает верно', () => {
        cy.clock()
        cy.get('@inputValue').type(1)
    })
});