import { 
    circle,
    circleSmall, 
    circleText,
    defaultColor,
    changingColor,
    modifiedColor,
    head,
    tail,
    index
} from "../constans";

import { DELAY_IN_MS } from '../../../src/constants/delays'

describe('Тест страницы List', () => {
    beforeEach(() => {
        cy.visit('/list')
        cy.get('[data-testid="listInputValueTest"]').as('inputValue')
        cy.get('[data-testid="listAddToHeadBtn"]').as('addToHeadBtn')
        cy.get('[data-testid="listAddToTailBtn"]').as('addToTailBtn')
        cy.get('[data-testid="listDeleteFromHeadBtn"]').as('deleteFromHeadBtn')
        cy.get('[data-testid="listDeleteFromTailBtn"]').as('deleteFromTailBtn')
        cy.get('[data-testid="listInputIndexTest"]').as('inputIndex')
        cy.get('[data-testid="listAddByIndexBtn"]').as('addByIndex')
        cy.get('[data-testid="listDeleteByIndexBtn"]').as('deleteByIndex')
        cy.get('[data-testid="circleTest"]').as('circle')
        cy.get('[data-testid="arrowTest"]').as('arrow')
    });
    it('Кнопка недоступна при пустом инпуте', () => {
        cy.get('@inputValue').should('be.empty')
        cy.get('@addToHeadBtn').should('be.disabled')
        cy.get('@addToTailBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
        cy.get('@inputIndex').should('be.empty')
        cy.get('@addByIndex').should('be.disabled')
        cy.get('@deleteByIndex').should('be.disabled')
    });
    it('Дефолтный список рендерится верно', () => {
        cy.get(circle)
        .should('have.length', 4)
        .should('have.css', 'border-color', defaultColor)
        cy.get('@arrow')
        .should('have.length', 3)
        cy.get(head).eq(0).contains('head')
        cy.get(tail).eq(3).contains('tail')
        cy.get(index).should('have.length', 4)
    });
    it('Добавление элемента в head работает верно', () => {
        cy.clock()
        cy.get(circle)
        .should('have.length', 4)
        cy.get('@inputValue').type('1')
        cy.get('@addToHeadBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled')
        cy.get('@addToHeadBtn').should('be.enabled').click()
        cy.get('@addToTailBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.get(circleSmall)
        .should('have.length', 1)
        .should('have.css', 'border-color', changingColor)
        .contains('1')
        cy.tick(DELAY_IN_MS)
        cy.get(circleSmall).should('not.exist')
        cy.get(circle)
        .should('have.length', 5)
        .eq(0).should('have.css', 'border-color', modifiedColor)
        .contains('1')
        cy.get(head).eq(0).contains('head')
        cy.get('div[data-testid="tailTest"]').eq(4).contains('tail')
        cy.get('@arrow')
        .should('have.length', 4)
        cy.tick(DELAY_IN_MS)
        cy.get(circle).should('have.length', 5)
        .eq(0)
        .should('have.css', 'border-color', defaultColor)
        cy.get('@inputValue').should('be.empty')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
    it('Добавление элемента в tail работает верно', () => {
        cy.clock()
        cy.get(circle)
        .should('have.length', 4)
        cy.get('@inputValue').type('5')
        cy.get('@addToHeadBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled').click()
        cy.get('@addToHeadBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.get(circleSmall)
        .should('have.length', 1)
        .should('have.css', 'border-color', changingColor)
        .contains('5')
        cy.tick(DELAY_IN_MS)
        cy.get(circleSmall).should('not.exist')
        cy.get(circle)
        .should('have.length', 5)
        .eq(4).should('have.css', 'border-color', modifiedColor)
        .contains('5')
        cy.get('div[data-testid="tailTest"]').eq(4).contains('tail')
        cy.get('@arrow')
        .should('have.length', 4)
        cy.tick(DELAY_IN_MS)
        cy.get(circle).should('have.length', 5)
        .eq(4)
        .should('have.css', 'border-color', defaultColor)
        cy.get('@inputValue').should('be.empty')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
    it('Добавление элемента по индексу работает верно', () => {
        cy.clock()
        cy.get('@circle')
        .should('have.length', 4)
        cy.get('@inputValue').type('1')
        cy.get('@addToHeadBtn').should('be.enabled')
        cy.get('@addToTailBtn').should('be.enabled')
        cy.get('@inputIndex').type('2')
        cy.get('@addByIndex').should('be.enabled')
        cy.get('@deleteByIndex').should('be.enabled')
        cy.get('@addByIndex').click()
        cy.get('@addToHeadBtn').should('be.disabled')
        cy.get('@addToTailBtn').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.get('@deleteByIndex').should('be.disabled')
        cy.get(circleSmall)
        .should('have.css', 'border-color', changingColor)
        cy.get(circleText)
        .eq(0)
        .contains('1')
        cy.tick(DELAY_IN_MS)
        cy.get('@circle')
        .eq(0)
        .should('have.css', 'border-color', changingColor)
        cy.get(circleText)
        .eq(1)
        .contains('1')
        cy.tick(DELAY_IN_MS)
        cy.get('@circle')
        .eq(1)
        .should('have.css', 'border-color', changingColor)
        cy.get(circleText)
        .eq(2)
        .contains('1')
        cy.tick(DELAY_IN_MS)
        cy.get('@circle')
        .eq(2)
        .should('have.css', 'border-color', modifiedColor)
        .contains('1')
        cy.tick(DELAY_IN_MS)
        cy.get('@circle')
        .eq(2)
        .should('have.css', 'border-color', defaultColor)
        .contains('1')
        cy.get('@circle').should('have.length', 5)
        cy.get('@addByIndex').should('be.disabled')
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
    it('Удаление элемента по индексу работает верно', () => {
        cy.clock()
        cy.get(circle)
        .should('have.length', 4)
        cy.get('@inputIndex').type('2')
        cy.get('@deleteByIndex').should('be.enabled')
        cy.get('@deleteByIndex').click()
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(0)
        .should('have.css', 'border-color', changingColor)
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(1)
        .should('have.css', 'border-color', changingColor)
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(2)
        .should('have.css', 'border-color', changingColor)
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(2)
        .should('have.css', 'border-color', defaultColor)
        .should('have.text', '')
        cy.get(circleSmall)
        .should('have.css', 'border-color', changingColor)
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .should('have.length', 3)
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
    it('Удаление элемента из tail рботает верно', () => {
        cy.clock()
        cy.get(circle)
        .should('have.length', 4)
        cy.get('@deleteFromHeadBtn').should('be.enabled')
        cy.get('@deleteFromTailBtn').should('be.enabled').click()
        cy.get('@deleteFromHeadBtn').should('be.disabled')
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(3)
        .should('have.text', '')
        cy.get(circleSmall)
        .should('have.css', 'border-color', changingColor)
        cy.get(circle)
        .should('have.length', 3)
        cy.get(tail).eq(2)
        cy.get('@deleteFromHeadBtn').should('be.enabled')
    });
    it('Удаление элемента из head рботает верно', () => {
        cy.clock()
        cy.get(circle)
        .should('have.length', 4)
        cy.get('@deleteFromTailBtn').should('be.enabled')
        cy.get('@deleteFromHeadBtn').should('be.enabled').click()
        cy.get('@deleteFromTailBtn').should('be.disabled')
        cy.tick(DELAY_IN_MS)
        cy.get(circle)
        .eq(0)
        .should('have.text', '')
        cy.get(circleSmall)
        .should('have.css', 'border-color', changingColor)
        cy.get(circle)
        .should('have.length', 3)
        cy.get(head).eq(0)
        cy.get('@deleteFromTailBtn').should('be.enabled')
    });
});